version: "3.8"

services:
  logitechno_site:
    container_name: logitechno_site
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx
